# Generated by Django 2.0.1 on 2018-02-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_headlines_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_headline', models.CharField(max_length=200)),
                ('headline_status', models.CharField(max_length=5)),
            ],
        ),
    ]
