# Generated by Django 2.0.1 on 2018-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAlgorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fake_news_headlines_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('headline_status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='real_news_headlines_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('headline_status', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='news_headlines_dataset',
        ),
    ]
