# Generated by Django 2.0.1 on 2018-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernewsheadline',
            old_name='headline_text',
            new_name='user_headline',
        ),
        migrations.AlterField(
            model_name='usernewsheadline',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
