# Generated by Django 2.0.1 on 2018-02-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectWebsite', '0002_auto_20180212_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernewsheadline',
            name='pub_date',
        ),
    ]
