# Generated by Django 2.0.1 on 2018-02-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectWebsite', '0003_remove_usernewsheadline_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_headline_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_headline', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserNewsHeadline',
        ),
    ]
