# Generated by Django 2.0.1 on 2018-02-13 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectWebsite', '0004_auto_20180213_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_headline_model',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='user_headline_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
